### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by Aericio** [jasonwynn10/MyPlot#4]
# FIXED

## Reproducing the issue
Startup server, run commands, etc
## Client information
OS: Windows
Core: ClearSky
php: 7.0.10
Zend: 3.0.0
## Optional information
```
[05:55:42] [Server thread/CRITICAL]: Unhandled exception executing command 'p claim' in plot: Call to a member function bindValue() on boolean
[05:55:42] [Server thread/CRITICAL]: Error: "Call to a member function bindValue() on boolean" (EXCEPTION) in "/MyPlot_v0.1.9.phar/src/MyPlot/provider/SQLiteDataProvider" at line 116
[05:55:42] [Server thread/DEBUG]: #0 /MyPlot_v0.1.9.phar/src/MyPlot/subcommand/ClaimSubCommand(23): MyPlot\MyPlot->getPlotByPosition(pocketmine\level\Position Position(level=Plots,x=3061.6594238281,y=76.187060241699,z=-3021.3586425781))
[05:55:42] [Server thread/DEBUG]: #1 /MyPlot_v0.1.9.phar/src/MyPlot/Commands(94): MyPlot\subcommand\ClaimSubCommand->execute(pocketmine\Player Player(3), array Array())
[05:55:42] [Server thread/DEBUG]: #2 /src/pocketmine/command/SimpleCommandMap(181): MyPlot\Commands->execute(pocketmine\Player Player(3), string p, array Array())
[05:55:42] [Server thread/DEBUG]: #3 /src/pocketmine/Server(2015): pocketmine\command\SimpleCommandMap->dispatch(pocketmine\Player Player(3), string p claim)
[05:55:42] [Server thread/DEBUG]: #4 /src/pocketmine/Player(2690): pocketmine\Server->dispatchCommand(pocketmine\Player Player(3), string p claim)
[05:55:42] [Server thread/DEBUG]: #5 /src/pocketmine/network/Network(217): pocketmine\Player->handleDataPacket(pocketmine\network\protocol\TextPacket object)
[05:55:42] [Server thread/DEBUG]: #6 /src/pocketmine/Player(1959): pocketmine\network\Network->processBatch(pocketmine\network\protocol\BatchPacket object, pocketmine\Player Player(3))
[05:55:42] [Server thread/DEBUG]: #7 /src/pocketmine/network/RakLibInterface(140): pocketmine\Player->handleDataPacket(pocketmine\network\protocol\BatchPacket object)
[05:55:42] [Server thread/DEBUG]: #8 /src/raklib/server/ServerHandler(78): pocketmine\network\RakLibInterface->handleEncapsulated(string 61.6.230.248:4088, raklib\protocol\EncapsulatedPacket `.`"...........&x.c``.bgd....K...(.L*.a../PH.I....^..., integer 0)
[05:55:42] [Server thread/DEBUG]: #9 /src/pocketmine/network/RakLibInterface(68): raklib\server\ServerHandler->handlePacket(boolean)
[05:55:42] [Server thread/DEBUG]: #10 /src/pocketmine/network/Network(127): pocketmine\network\RakLibInterface->process(boolean)
[05:55:42] [Server thread/DEBUG]: #11 /src/pocketmine/Server(2563): pocketmine\network\Network->processInterfaces(boolean)
[05:55:42] [Server thread/DEBUG]: #12 /src/pocketmine/Server(2304): pocketmine\Server->tick(boolean)
[05:55:42] [Server thread/DEBUG]: #13 /src/pocketmine/Server(2182): pocketmine\Server->tickProcessor(boolean)
[05:55:42] [Server thread/DEBUG]: #14 /src/pocketmine/Server(1777): pocketmine\Server->start(boolean)
[05:55:42] [Server thread/DEBUG]: #15 /src/pocketmine/PocketMine(449): pocketmine\Server->__construct(pocketmine\CompatibleClassLoader object, pocketmine\utils\MainLogger object, string phar://C:\Users\garre_000\Desktop\Network\ClearSky.phar/, string C:\Users\garre_000\Desktop\Network\, string C:\Users\garre_000\Desktop\Network\plugins\)
[05:55:42] [Server thread/DEBUG]: #16 (1): require_once(string phar://C:/Users/garre_000/Desktop/Network/ClearSky.phar/src/pocketmine/PocketMine.php)
```
All commands have errors, I don't feel like listing them all.
Also. /p help is empty.

**Comment by jasonwynn10** [comment]
This is a known issue that I will be fixing shortly

**Comment by jasonwynn10** [comment]
I believe this error was caused by an unbound sql column

**Comment by jasonwynn10** [comment]
@Aericio can you test the fix on your server?

**Comment by Aericio** [comment]
Ok.

**Comment by jasonwynn10** [comment]
anything in the way of bugs? @Aericio

**Comment by Aericio** [comment]
```
Fatal error: Cannot declare class MyPlot\subcommand\BiomeSubCommand, because the name ismesSubCommand.php on line 0
[06:11:53] [Server thread/EMERGENCY]: An unrecoverable error has occurred and the server
[06:11:53] [Server thread/EMERGENCY]: Please upload the "C:\Users\Aericio\Desktop\Minecrlink to the Bug Reporting page. Give as much info as you can.
```
```
ClearSky Crash Dump Tue Sep 27 06:11:53 CEST 2016

Error: Cannot declare class MyPlot\subcommand\BiomeSubCommand, because the name is already in use
File: /MyPlot-master/src/MyPlot/subcommand/BiomesSubCommand
Line: 0
Type: E_COMPILE_ERROR

THIS CRASH WAS CAUSED BY A PLUGIN
BAD PLUGIN: MyPlot v0.3.6_alpha

Code:
[1] <?php
[2] namespace MyPlot\subcommand;
[3] 
[4] use pocketmine\command\CommandSender;
[5] use pocketmine\utils\TextFormat;
[6] use pocketmine\level\generator\biome\Biome;
[7] 
[8] class BiomeSubCommand extends SubCommand {
[9]     private $biomes = [
[10]         "PLAINS" => Biome::PLAINS,

Backtrace:
#0 (): pocketmine\Server->crashDump(boolean)
```

**Comment by jasonwynn10** [comment]
Is that the only one? It was caused by a typo in the class declaration

**Comment by jasonwynn10** [comment]
anything else @Aericio ?

**Comment by Aericio** [comment]
Testing again.

**Comment by Aericio** [comment]
```
Fatal error: Uncaught ClassNotFoundException: Class MyPlot\SetOwnerSubCommand not found in phar://C:/Users/Aericio/Desktop/Minecraft PE/ClearSky.phar/src/spl/BaseClassLoader.php:128
Stack trace:
#0 [internal function]: BaseClassLoader->loadClass('MyPlot\\SetOwner...')
#1 C:\Users\Aericio\Desktop\Minecraft PE\plugins\MyPlot-master\src\MyPlot\Commands.php(65): spl_autoload_call('MyPlot\\SetOwner...')
#2 C:\Users\Aericio\Desktop\Minecraft PE\plugins\MyPlot-master\src\MyPlot\MyPlot.php(463): MyPlot\Commands->__construct(Object(MyPlot\MyPlot))
#3 phar://C:/Users/Aericio/Desktop/Minecraft PE/ClearSky.phar/src/pocketmine/plugin/PluginBase.php(66): MyPlot\MyPlot->onEnable()
#4 phar://C:/Users/Aericio/Desktop/Minecraft PE/plugins/DevTools.phar/src/FolderPluginLoader/FolderPluginLoader.php(125): pocketmine\plugin\PluginBase->setEnabled(true)
#5 phar://C:/Users/Aericio/Desktop/Minecraft PE/ClearSky.phar/src/pocketmine/plugin/PluginManager.php(574): FolderPluginLoader\FolderPluginLoader->enablePlugin(Object(MyPlot\MyPlot))
#6 phar:// in phar://C:/Users/Aericio/Desktop/Minecraft PE/ClearSky.phar/src/spl/BaseClassLoader.php on line 128
[05:51:17] [Server thread/EMERGENCY]: An unrecoverable error has occurred and the server has crashed. Creating a crash dump
[05:51:17] [Server thread/EMERGENCY]: Please upload the "C:\Users\Aericio\Desktop\Minecraft PE\crashdumps/CrashDump_Wed_Sep_28-05.51.17-CEST_2016.log" file to the Crash Archive and submit the link to the Bug Reporting page. Give as much info as you can.
```
```
ClearSky Crash Dump Wed Sep 28 05:51:17 CEST 2016

Error: Uncaught ClassNotFoundException: Class MyPlot\SetOwnerSubCommand not found in phar://C:/Users/Aericio/Desktop/Minecraft PE/ClearSky.phar/src/spl/BaseClassLoader.php:128
File: /src/spl/BaseClassLoader
Line: 128
Type: E_ERROR

THIS CRASH WAS CAUSED BY A PLUGIN

Code:
[119] 
[120] 	        if(method_exists($name, "onClassLoaded") and (new ReflectionClass($name))->getMethod("onClassLoaded")->isStatic()){
[121] 		        $name::onClassLoaded();
[122] 	        }
[123] 	        
[124] 	        $this->classes[] = $name;
[125] 
[126]             return true;
[127]         }elseif($this->getParent() === null){
[128] 	        throw new ClassNotFoundException("Class $name not found");
[129]         }
[130] 
[131]         return false;
[132]     }
[133] 
[134]     /**
[135]      * Returns the path for the class, if any
[136]      *
[137]      * @param string $name
[138]      *

Backtrace:
#0 (): pocketmine\Server->crashDump(boolean)
```

**Comment by jasonwynn10** [comment]
that one was caused by me not putting a namespace reference in the Commands file

**Comment by Aericio** [comment]
Why custom help page? Old one seemed fine.
```
p help
[04:55:58] [Server thread/INFO]: =======+--MyPlot--+=======

Deprecated: Non-static method MyPlot\Commands::getCommands() should not be called statically in C:\Users\Aericio\Desktop\Minecraft PE\plugins\MyPlot-master\src\MyPlot\Commands.php on line 81

Fatal error: Uncaught Error: Using $this when not in object context in C:\Users\Aericio\Desktop\Minecraft PE\plugins\MyPlot-master\src\MyPlot\Commands.php:74
Stack trace:
#0 C:\Users\Aericio\Desktop\Minecraft PE\plugins\MyPlot-master\src\MyPlot\Commands.php(81): MyPlot\Commands::getCommands()
#1 C:\Users\Aericio\Desktop\Minecraft PE\plugins\MyPlot-master\src\MyPlot\subcommand\HelpSubCommand.php(16): MyPlot\Commands::getCmd()
#2 C:\Users\Aericio\Desktop\Minecraft PE\plugins\MyPlot-master\src\MyPlot\Commands.php(108): MyPlot\subcommand\HelpSubCommand->execute(Object(pocketmine\command\ConsoleCommandSender), Array)
#3 phar://C:/Users/Aericio/Desktop/Minecraft PE/ClearSky.phar/src/pocketmine/command/SimpleCommandMap.php(183): MyPlot\Commands->execute(Object(pocketmine\command\ConsoleCommandSender), 'p', Array)
#4 phar://C:/Users/Aericio/Desktop/Minecraft PE/ClearSky.phar/src/pocketmine/Server.php(2037): pocketmine\command\SimpleCommandMap->dispatch(Object(pocketmine\command\ConsoleCommandSender), 'p help')
#5 phar://C:/Users/ in C:\Users\Aericio\Desktop\Minecraft PE\plugins\MyPlot-master\src\MyPlot\Commands.php on line 74
[04:55:58] [Server thread/EMERGENCY]: An unrecoverable error has occurred and the server has crashed. Creating a crash dump
[04:55:58] [Server thread/EMERGENCY]: Please upload the "C:\Users\Aericio\Desktop\Minecraft PE\crashdumps/CrashDump_Thu_Sep_29-04.55.58-CEST_2016.log" file to the Crash Archive and submit the link to the Bug Reporting page. Give as much info as you can.
```
```
ClearSky Crash Dump Thu Sep 29 04:55:58 CEST 2016

Error: Uncaught Error: Using $this when not in object context in C:\Users\Aericio\Desktop\Minecraft PE\plugins\MyPlot-master\src\MyPlot\Commands.php:74
File: /MyPlot-master/src/MyPlot/Commands
Line: 74
Type: E_ERROR

THIS CRASH WAS CAUSED BY A PLUGIN
BAD PLUGIN: MyPlot v0.6.6_alpha

Code:
[65]         $this->loadSubCommand(new DoneSubCommand($plugin, "done"));
[66]         $this->loadSubCommand(new SetOwnerSubCommand($plugin, "setowner"));
[67]         $this->loadSubCommand(new ListSubCommand($plugin, "list"));
[68]     }
[69] 
[70]     /**
[71]      * @return subcommand\SubCommand[]
[72]      */
[73]     public function getCommands() {
[74]         return $this->subCommands;
[75]     }
[76] 
[77]     /**
[78]      * @return subcommand\SubCommand[]
[79]      */
[80]     public static function getCmd() {
[81]         return self::getCommands();
[82]     }
[83] 
[84]     private function loadSubCommand(SubCommand $command) {

Backtrace:
#0 (): pocketmine\Server->crashDump(boolean)

ClearSky version: 1.1 #377 [Protocol 83; API 2.0.0]
uname -a: Windows NT Windows 10.0 build 14393 (Windows 10) AMD64
PHP Version: 7.0.10
Zend version: 3.0.0
OS : WINNT, win
```

**Comment by Aericio** [comment]
@SalmonGER could probably help when he has free time. (aka whenever he's *not* coding)

**Comment by jasonwynn10** [comment]
I was told otherwise. The help page only worked on some peoples servers. I am making it so the plugin will work on php5 servers as well as php7

**Comment by Aericio** [comment]
Making run on php7 is faster though, isn't it?

**Comment by jasonwynn10** [comment]
yea but, some people are still running php5 for whatever their reasoning...

**Comment by jasonwynn10** [comment]
I reverted the help page partially in 66e3daa

**Comment by jasonwynn10** [comment]
anyway, are all the plugins commands working?

**Comment by jasonwynn10** [comment]
I am making the v1.0.0 Release Today

**Comment by Aericio** [comment]
Maybe seperate branches for php7 & php5. I'll test again after I finish homework.

**Comment by jasonwynn10** [comment]
I am making the release now

**Comment by Aericio** [comment]
Got it.
